### ISSUE TITLE
Add the option to respect certain labels on the original Trivy CRDs

### ISSUE THREAD

**Issue by sherifkayad** [fjogeleit/trivy-operator-polr-adapter#48]
Currently we configured the Trivy CRDs to respect the labels `owner` and `app` set on the resources to scan. This enables us to be able to filter e.g. by vulnerabilities belonging to a certain team or a certain application (at least from a Grafana perspective).

Maybe it would be a good idea to allow the adapter to also respect some of those labels and add them on the `ClusterPolicyReport` and `PolicyReport` objects it creates?

**Comment by fjogeleit** [comment]
With the new `applyLabels` value for each report you are able to define a list of labels to apply from the source report to the (Cluster)PolicyReport.

It's released as version `v0.2.0`.

**Comment by sherifkayad** [comment]
@fjogeleit I will give it a try right away! Thanks for the speedy work on that one.

**Comment by fjogeleit** [comment]
You're welcome. Currently the image build workflow builds the image. So it will be available soon

**Comment by sherifkayad** [comment]
@fjogeleit just wanted to assure that this works like charm!

```yaml
apiVersion: wgpolicyk8s.io/v1alpha2
kind: PolicyReport
metadata:
  creationTimestamp: '2022-11-30T13:14:11Z'
  generation: 1
  labels:
    owner: team-x
    app: my-test-app
    app.kubernetes.io/created-by: trivy-operator-polr-adapter
    trivy-operator.source: ConfigAuditReport
...
```

Just worth mentioning: I had to delete all the `(Cluster)PolicyReport` objects and then the adapter ran smoothly again and generated all reports with the right labels.
